# test for good behavior of data manipulation functions

context("data manipulation")

test_that("makeModelData and makeRawData are inversions of each other", {
  data(Phosphorus)
  moddat1 = makeModelData(Phosphorus)
  rawdat1 = makeModelData(makeRawData(moddat1))[names(moddat1)]
  attributes(rawdat1) = NULL
  attributes(moddat1) = NULL
  expect_equal(moddat1, rawdat1)

  data(rc_synth)
  moddat2 = makeModelData(rc_synth)
  rawdat2 = makeModelData(makeRawData(moddat2))[names(moddat2)]
  attributes(rawdat2) = NULL
  attributes(moddat2) = NULL
  expect_equal(moddat2, rawdat2)
})

test_that("getData works for rcgams", {
  data(Phosphorus)
  pdat = makeModelData(Phosphorus)
  mod2 = rcgam(c ~ s(q) + s(doy, bs = "cc", k = 4) + s(time), pdat)

  expect_is(getData(mod2, type = "rcData"), "rcData")
  expect_is(getData(mod2, type = "raw"), "data.frame")
})


test_that("rcdata object is recoverable from rcgam object", {
  data(Phosphorus)
  pdat = makeModelData(Phosphorus)
  mod2 = rcgam(c ~ s(q) + s(doy, bs = "cc", k = 4) + s(time), pdat)

  expect_is(getData(mod2, type = "rcData"), "rcData")
  expect_is(getData(mod2, type = "raw"), "data.frame")

  oc <- function(df) df[order(names(df))]
  expect_equal(oc(makeModelData(getData(mod2, type = "raw"))), oc(getData(mod2, type = "rcData")))
  expect_equal(oc(makeRawData(getData(mod2, type = "rcData"))), oc(getData(mod2, type = "raw")))
})


# Transformation functions

test_that("functions generated by transf return numeric", {
  link1 = make.link("log")
  tfm = transf(link1, 5, 3)

  expect_is(tfm$trans(rexp(10)), "numeric")
  expect_is(tfm$invert(rexp(10)), "numeric")

  data(Phosphorus)
  mod2 <- rcgam(c ~ s(q) + s(doy, bs = "cc", k = 4) + s(time), Phosphorus)

  expect_is(mod2$transform$cinvert(exp(10)), "numeric")
})

test_that("Date transformations go to and fro", {
  testdates = seq.Date(Sys.Date(), Sys.Date() + 19, 1)
  tfm = transf(testdates, mean(testdates))

  expect_is(tfm$trans(testdates), "numeric")
  expect_equal(tfm$invert(tfm$trans(testdates)), testdates)
})


test_that("subsetting preserves attributes in rcData objects", {
  data(Phosphorus)
  pdat = makeModelData(Phosphorus)
  atnames <- c("class", "stats", "transform", "units", "names")

  expect_identical(attributes(pdat[1:10,])[atnames], attributes(pdat)[atnames])
})


test_that("load unit conversion works", {
  expect_less_than(abs(calcLoad(flow = 1, conc = 1) - 3600 * 24 * 28.3168 / 1000000),
                   0.0001)
})
